components:
  schemas:
    Gender:
      $ref: '#/components/schemas/Gender'
    Role:
      $ref: '#/components/schemas/Role'
    Admin:
      $ref: '#/components/schemas/Admin'
    Error:
      $ref: '#/components/schemas/Error'
