components:
  schemas:
    Role:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          enum: [admin, user]

    Admin:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          $ref: '#/components/schemas/Role'

    Error:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
