components:
  schemas:
    Gender:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          enum: [Male, Female, 'Prefer not to say']

    Role:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          enum: [admin, user]

    Admin:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          $ref: '#/components/schemas/Role'

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        avatar:
          type: string
        phone:
          type: string
        email:
          type: string
          format: email
        gender:
          $ref: '#/components/schemas/Gender'
        role:
          $ref: '#/components/schemas/Role'

    Error:
      type: object
      properties:
        message:
          type: string
        stack:
          type: string | null
