version: '3.7'

services:
  db:
    volumes:
      - db_prod:/data/db
      - ./dump:/dump
    secrets:
      - DB_ROOT_USERNAME
      - DB_ROOT_PASSWORD
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
    environment:
      - MONGO_INITDB_ROOT_USERNAME=/run/secrets/DB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=/run/secrets/DB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=/run/secrets/DB_NAME
      - MONGO_USERNAME=/run/secrets/DB_USER
      - MONGO_PASSWORD=/run/secrets/DB_PASSWORD
    configs:
      - source: MONGO_CONFIG
        target: /docker-entrypoint-initdb.d/mongo-init.sh:ro

  cache:
    command:
      - bash
      - -c
      - |
        [ "$$REDIS_PASSWORD_FILE" ] \
          && (cat "$$REDIS_PASSWORD_FILE" | xargs -0 redis-server --appendonly yes --requirepass) \
          || redis-server --appendonly yes
    volumes:
      - cache_prod:/data
    secrets:
      - REDIS_PASSWORD
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD

volumes:
  db_prod:
    driver: local
  cache_prod:
    driver: local

secrets:
  DB_ROOT_USER:
    file: ./secrets/DB_ROOT_USER
    name: DB_ROOT_USER_20231023T163900
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD
    name: DB_ROOT_PASSWORD_20231023T163900
  DB_NAME:
    file: ./secrets/DB_NAME
    name: DB_NAME_20231023T163900
  DB_USER:
    file: ./secrets/DB_USER
    name: DB_USER_20231023T163900
  DB_PASSWORD:
    file: ./secrets/DB_PASSWORD
    name: DB_PASSWORD_20231023T163900
  REDIS_PASSWORD:
    file: ./secrets/REDIS_PASSWORD
    name: REDIS_PASSWORD_20231023T163900

configs:
  MONGO_CONFIG:
    file: ./mongo-init.sh
    name: MONGO_CONFIG_20230209113700

networks:
  app:
    driver: overlay
