version: '3.7'

services:
  web:
    tty: true
    image: nginx:1.23
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.html:/usr/share/nginx/html/index.html

  server:
    tty: true
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    build:
      context: .
      target: dev
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./:/app
    env_file:
      - .env
    command: npm run start:dev

  db:
    tty: true
    restart: unless-stopped
    volumes:
      - db_dev:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
      - '5433:5432'

  adminer:
    tty: true
    restart: unless-stopped
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app

  cache:
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    tty: true
    restart: unless-stopped
    volumes:
      - cache_dev:/data
    env_file:
      - .env

volumes:
  db_dev:
    driver: local
  cache_dev:
    driver: local

networks:
  app:
    driver: bridge
