version: '3.7'

services:
  db:
    volumes:
      - db_prod:/var/lib/postgresql/data
    secrets:
      - DB_USER
      - DB_PASS
      - DB_NAME
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/DB_PASS
      - POSTGRES_USER_FILE=/run/secrets/DB_USER
      - POSTGRES_DB_FILE=/run/secrets/DB_NAME

  cache:
    command:
      - bash
      - -c
      - |
        [ "$$REDIS_PASSWORD_FILE" ] \
          && (cat "$$REDIS_PASSWORD_FILE" | xargs -0 redis-server --appendonly yes --requirepass) \
          || redis-server --appendonly yes
    volumes:
      - cache_prod:/data
    secrets:
      - REDIS_PASSWORD
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD

volumes:
  db_prod:
    driver: local
  cache_prod:
    driver: local

secrets:
  DB_USER:
    file: ./secrets/DB_USER
    name: DB_USER_20230209113700
  DB_PASS:
    file: ./secrets/DB_PASS
    name: DB_PASS_20230209113700
  DB_NAME:
    file: ./secrets/DB_NAME
    name: DB_NAME_20230209113700
  REDIS_PASSWORD:
    file: ./secrets/REDIS_PASSWORD
    name: REDIS_PASSWORD_20230209113700

networks:
  app:
    driver: overlay
