version: '3.7'

services:
  web:
    image: nginx:1.23
    depends_on:
      - server
    networks:
      - app
    ports:
      - 80:80
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/conf.d/default.conf
      - source: NGINX_HTML
        target: /usr/share/nginx/html/index.html
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s

  server:
    image: 127.0.0.1:5000/ts-server:1.0.0
    command: npm run start
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s
    secrets:
      - APP_PORT
      - APP_PROTOCOL
      - APP_HOST
      - BCRYPT_SALT
      - BCRYPT_MAX_BYTES
      - JWT_ACCESS_SECRET
      - JWT_ACCESS_EXPIRY
      - JWT_REFRESH_SECRET
      - JWT_REFRESH_EXPIRY
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_PORT
      - REDIS_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - SESSION_SECRET
    environment:
      - APP_PORT_FILE=/run/secrets/APP_PORT
      - APP_PROTOCOL_FILE=/run/secrets/APP_PROTOCOL
      - APP_HOST_FILE=/run/secrets/APP_HOST
      - BCRYPT_SALT_FILE=/run/secrets/BCRYPT_SALT
      - BCRYPT_MAX_BYTES_FILE=/run/secrets/BCRYPT_MAX_BYTES
      - JWT_ACCESS_SECRET_FILE=/run/secrets/JWT_ACCESS_SECRET
      - JWT_ACCESS_EXPIRY_FILE=/run/secrets/JWT_ACCESS_EXPIRY
      - JWT_REFRESH_SECRET_FILE=/run/secrets/JWT_REFRESH_SECRET
      - JWT_REFRESH_EXPIRY_FILE=/run/secrets/JWT_REFRESH_EXPIRY
      - DB_HOST_FILE=/run/secrets/DB_HOST
      - DB_USER_FILE=/run/secrets/DB_USER
      - DB_PASS_FILE=/run/secrets/DB_PASS
      - DB_NAME_FILE=/run/secrets/DB_NAME
      - DB_PORT_FILE=/run/secrets/DB_PORT
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
      - REDIS_HOST_FILE=/run/secrets/REDIS_HOST
      - REDIS_PORT_FILE=/run/secrets/REDIS_PORT
      - SESSION_SECRET_FILE=/run/secrets/SESSION_SECRET

  db:
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - db_prod:/var/lib/postgresql/data
    secrets:
      - DB_USER
      - DB_PASS
      - DB_NAME
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/DB_PASS
      - POSTGRES_USER_FILE=/run/secrets/DB_USER
      - POSTGRES_DB_FILE=/run/secrets/DB_NAME

  cache:
    deploy:
      placement:
        constraints:
          - node.role == manager
    command:
      - bash
      - -c
      - |
        [ "$$REDIS_PASSWORD_FILE" ] \
          && (cat "$$REDIS_PASSWORD_FILE" | xargs -0 redis-server --appendonly yes --requirepass) \
          || redis-server --appendonly yes
    volumes:
      - cache_prod:/data
    secrets:
      - REDIS_PASSWORD
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD

volumes:
  db_prod:
    driver: local
  cache_prod:
    driver: local

secrets:
  APP_PORT:
    file: ./secrets/APP_PORT
    name: APP_PORT_20230209113700
  APP_PROTOCOL:
    file: ./secrets/APP_PROTOCOL
    name: APP_PROTOCOL_20230209113700
  APP_HOST:
    file: ./secrets/APP_HOST
    name: APP_HOST_20230209113700
  BCRYPT_SALT:
    file: ./secrets/BCRYPT_SALT
    name: BCRYPT_SALT_20230209113700
  BCRYPT_MAX_BYTES:
    file: ./secrets/BCRYPT_MAX_BYTES
    name: BCRYPT_MAX_BYTES_20230209113700
  JWT_ACCESS:
    file: ./secrets/JWT_ACCESS
    name: JWT_ACCESS_20230209113700
  JWT_ACCESS_LIFE:
    file: ./secrets/JWT_ACCESS_LIFE
    name: JWT_ACCESS_LIFE_20230209113700
  JWT_REFRESH:
    file: ./secrets/JWT_REFRESH
    name: JWT_REFRESH_20230209113700
  JWT_REFRESH_LIFE:
    file: ./secrets/JWT_REFRESH_LIFE
    name: JWT_REFRESH_LIFE_20230209113700
  DB_HOST:
    file: ./secrets/DB_HOST
    name: DB_HOST_20230209113700
  DB_USER:
    file: ./secrets/DB_USER
    name: DB_USER_20230209113700
  DB_PASS:
    file: ./secrets/DB_PASS
    name: DB_PASS_20230209113700
  DB_NAME:
    file: ./secrets/DB_NAME
    name: DB_NAME_20230209113700
  DB_PORT:
    file: ./secrets/DB_PORT
    name: DB_PORT_20230209113700
  REDIS_PASSWORD:
    file: ./secrets/REDIS_PASSWORD
    name: REDIS_PASSWORD_20230209113700
  REDIS_HOST:
    file: ./secrets/REDIS_HOST
    name: REDIS_HOST_20230209113700
  REDIS_PORT:
    file: ./secrets/REDIS_PORT
    name: REDIS_PORT_20230209113700
  SESSION_SECRET:
    file: ./secrets/SESSION_SECRET
    name: SESSION_SECRET_20230209113700

configs:
  NGINX_CONFIG:
    file: ./nginx/default.conf
    name: NGINX_CONFIG_20230209113700
  NGINX_HTML:
    file: ./nginx/default.html
    name: NGINX_HTML_20230209113700

networks:
  app:
    driver: overlay
