version: '3.7'

services:
  server:
    depends_on:
      - db
    networks:
      - app
    
  db:
    image: postgres:15.1-bullseye
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

  cache:
    image: redis:7-bullseye
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app
