version: '3.7'

services:
  server:
    tty: true
    depends_on:
      psqldb:
        condition: service_healthy
    build:
      context: .
      target: dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 8080:8080
    command: npm run start:dev

  psqldb:
    tty: true
    restart: on-failure
    volumes:
      - psql_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  psql_dev:
    driver: local

networks:
  app:
    driver: bridge
