version: '3.7'

services:
  web:
    image: nginx:1.23
    depends_on:
      - server
    networks:
      - app
    ports:
      - 80:80

  server:
    depends_on:
      - psqldb
    networks:
      - app
    secrets:
      - APP_PORT
      - APP_PROTOCOL
      - APP_HOST
      - BCRYPT_SALT
      - BCRYPT_MAX_BYTES
      - JWT_SECRET
      - JWT_EXPIRES
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_PORT
      - CRON_REMOVE_TEMP
    environment:
      - APP_PORT_FILE=/run/secrets/APP_PORT
      - APP_PROTOCOL_FILE=/run/secrets/APP_PROTOCOL
      - APP_HOST_FILE=/run/secrets/APP_HOST
      - BCRYPT_SALT_FILE=/run/secrets/BCRYPT_SALT
      - BCRYPT_MAX_BYTES_FILE=/run/secrets/BCRYPT_MAX_BYTES
      - JWT_SECRET_FILE=/run/secrets/JWT_SECRET
      - JWT_EXPIRES_FILE=/run/secrets/JWT_EXPIRES
      - DB_HOST_FILE=/run/secrets/DB_HOST
      - DB_USER_FILE=/run/secrets/DB_USER
      - DB_PASS_FILE=/run/secrets/DB_PASS
      - DB_NAME_FILE=/run/secrets/DB_NAME
      - DB_PORT_FILE=/run/secrets/DB_PORT
      - CRON_REMOVE_TEMP_FILE=/run/secrets/CRON_REMOVE_TEMP

  psqldb:
    image: postgres:15.1-bullseye
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app
    secrets:
      - DB_USER
      - DB_PASS
      - DB_NAME
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/DB_PASS
      - POSTGRES_USER_FILE=/run/secrets/DB_USER
      - POSTGRES_DB_FILE=/run/secrets/DB_NAME

secrets:
  APP_PORT:
    file: ./secrets/APP_PORT
    name: APP_PORT_20230206220300
  APP_PROTOCOL:
    file: ./secrets/APP_PROTOCOL
    name: APP_PROTOCOL_20230206220300
  APP_HOST:
    file: ./secrets/APP_HOST
    name: APP_HOST_20230206220300
  BCRYPT_SALT:
    file: ./secrets/BCRYPT_SALT
    name: BCRYPT_SALT_20230206220300
  BCRYPT_MAX_BYTES:
    file: ./secrets/BCRYPT_MAX_BYTES
    name: BCRYPT_MAX_BYTES_20230206220300
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
    name: JWT_SECRET_20230206220300
  JWT_EXPIRES:
    file: ./secrets/JWT_EXPIRES
    name: JWT_EXPIRES_20230206220300
  DB_HOST:
    file: ./secrets/DB_HOST
    name: DB_HOST_20230206220300
  DB_USER:
    file: ./secrets/DB_USER
    name: DB_USER_20230206220300
  DB_PASS:
    file: ./secrets/DB_PASS
    name: DB_PASS_20230206220300
  DB_NAME:
    file: ./secrets/DB_NAME
    name: DB_NAME_20230206220300
  DB_PORT:
    file: ./secrets/DB_PORT
    name: DB_PORT_20230206220300
  CRON_REMOVE_TEMP:
    file: ./secrets/CRON_REMOVE_TEMP
    name: CRON_REMOVE_TEMP_20230206220300
