version: '3.7'

services:
  web:
    tty: true
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.html:/usr/share/nginx/html/index.html

  server:
    tty: true
    depends_on:
      psqldb:
        condition: service_healthy
    build:
      context: .
      target: dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run start:dev

  psqldb:
    tty: true
    restart: on-failure
    volumes:
      - psql_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  psql_dev:
    driver: local

networks:
  app:
    driver: bridge
