version: '3.7'

services:
  web:
    tty: true
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped

  server:
    tty: true
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    build:
      context: .
      target: dev
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run start:dev

  db:
    tty: true
    restart: unless-stopped
    volumes:
      - db_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    tty: true
    restart: unless-stopped
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - accounts-app

  cache:
    tty: true
    restart: unless-stopped
    volumes:
      - cache_dev:/data
    networks:
      - accounts-app

volumes:
  db_dev:
    driver: local
  cache_dev:
    driver: local

networks:
  accounts-app:
    driver: bridge
