paths:
  /api/common/images:
    post:
      summary: Upload Image
      tags: [Common]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                uploadedFile:
                  type: string
                  format: binary
      responses:
        200:
          description: Returns path of the uploaded file
    get:
      summary: Image Buffer
      tags: [Common]
      parameters:
        - in: query
          name: filename
          schema:
            type: string
            required: true
            description: The path of the file
          example: temp/uuid-file-name.ext
      responses:
        200:
          description: file buffer according path name
    delete:
      summary: Delete Image
      tags: [Common]
      parameters:
        - in: query
          name: filename
          schema:
            type: string
            required: true
            description: The path of the file
          example: temp/uuid-file-name.ext
      responses:
        200:
          description: Returns deleted file confirmation
